# Generated by Django 2.1.3 on 2018-12-08 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliado',
            options={'ordering': ('-fecha_afiliacion',)},
        ),
        migrations.AddField(
            model_name='afiliado',
            name='fecha_afiliacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
